In [1]:
import cv2

def detect_faces():
    # 웹캠을 켭니다.
    cap = cv2.VideoCapture(0)

    # 얼굴 인식을 위해 얼굴 검출기를 로드합니다.
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

    while True:
        # 웹캠으로부터 영상을 받아옵니다.
        ret, frame = cap.read()

        if not ret:
            break

        # 영상을 회색으로 변환합니다.
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # 얼굴을 검출합니다.
        # faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))
        faces = face_cascade.detectMultiScale(gray)

        # 검출된 얼굴 주위에 사각형을 그립니다.
        for (x, y, w, h) in faces:
            cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
            cv2.putText(frame, 'Face', (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

        # 결과 영상을 화면에 출력합니다.
        cv2.imshow('Face Detection', frame)

        # 'q'를 누르면 종료합니다.
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # 웹캠을 끕니다.
    cap.release()
    cv2.destroyAllWindows()

# 웹캠으로부터 얼굴을 인식합니다.
detect_faces()

In [ ]:
import datetime
import cv2

capture = cv2.VideoCapture("sample_1280x720_surfing_with_audio.avi")
fourcc = cv2.VideoWriter_fourcc(*'XVID')
record = False

while True:
    if(capture.get(cv2.CAP_PROP_POS_FRAMES) == capture.get(cv2.CAP_PROP_FRAME_COUNT)-1):
        capture.open("./deeplearning/opencv/sample_1280x720_surfing_with_audio.avi")

    ret, frame = capture.read()
    cv2.imshow("VideoFrame", frame)

    now = datetime.datetime.now().strftime("%d_%H-%M-%S")
    key = cv2.waitKey(33)

    if key == 27: #ESC
        break
    elif key == ord('c'):
        print("캡쳐")
        cv2.imwrite("C:/Users/gamec/Downloads/" + str(now) + ".png", frame)
    elif key == ord('r'):
        print("녹화 시작")
        record = True
        video = cv2.VideoWriter("C:/Users/gamec/Downloads/" + str(now) + ".avi", fourcc, 20.0, (frame.shape[1], frame.shape[0]))
    elif key == ord('s'):
        print("녹화 중지")
        record = False
        video.release()
        
    if record == True:
        print("녹화 중..")
        video.write(frame)

capture.release()
cv2.destroyAllWindows()

In [2]:
import cv2
import numpy as np

def mouse_event(event, x, y, flags, param):
    print("event x y flags", event, x, y, flags)
    diff = 2
    global radius
    
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(param, (x, y), radius, (255, 0, 0), 2)
        cv2.imshow("draw", src)

    elif event == cv2.EVENT_MOUSEWHEEL:
        if flags > 0:
            radius += diff
        elif radius > 1:
            radius -= diff

radius = 5
src = np.full((500, 500, 3), 255, dtype=np.uint8)

cv2.imshow("draw", src)
cv2.setMouseCallback("draw", mouse_event, src)
cv2.waitKey()
cv2.destroyAllWindows()

event x y flags 0 484 405 0
event x y flags 0 453 389 0
event x y flags 0 422 372 0
event x y flags 0 395 356 0
event x y flags 0 368 343 0
event x y flags 0 346 329 0
event x y flags 0 329 318 0
event x y flags 0 314 309 0
event x y flags 0 302 302 0
event x y flags 0 289 293 0
event x y flags 0 279 286 0
event x y flags 0 268 279 0
event x y flags 0 260 273 0
event x y flags 0 252 266 0
event x y flags 0 244 259 0
event x y flags 0 238 253 0
event x y flags 0 233 247 0
event x y flags 0 228 241 0
event x y flags 0 224 236 0
event x y flags 0 221 232 0
event x y flags 0 218 227 0
event x y flags 0 216 224 0
event x y flags 0 214 221 0
event x y flags 0 212 218 0
event x y flags 0 210 216 0
event x y flags 0 209 214 0
event x y flags 0 207 211 0
event x y flags 0 205 208 0
event x y flags 0 204 205 0
event x y flags 0 203 202 0
event x y flags 0 203 200 0
event x y flags 0 203 199 0
event x y flags 0 203 198 0
event x y flags 1 203 198 1
event x y flags 4 203 198 0
event x y flags 0 20

In [3]:
#실습 5
import cv2

history = []
radius = 5

def mouse_event(event, x, y, flags, param):
    print("event x y flags", event, x, y, flags)
    diff = 2
    global radius

    if event == cv2.EVENT_RBUTTONDOWN:
        history.append((x, y))

    elif event == cv2.EVENT_MOUSEWHEEL:
        if flags > 0:
            radius += diff
        elif radius > 1:
            radius -= diff


capture = cv2.VideoCapture(0)
# capture.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
# capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

cv2.namedWindow("VideoFrame")
cv2.setMouseCallback("VideoFrame", mouse_event)

while cv2.waitKey(10) < 0:
    ret, frame = capture.read()
    for x, y in history:
        cv2.circle(frame, (x, y), radius, (255, 0, 0), 2)

    cv2.imshow("VideoFrame", frame)

capture.release()
cv2.destroyAllWindows()

event x y flags 0 517 367 0
event x y flags 0 517 367 0
event x y flags 0 517 367 0
event x y flags 0 517 368 0
event x y flags 0 512 368 0
event x y flags 0 508 367 0
event x y flags 0 488 370 0
event x y flags 0 479 371 0
event x y flags 0 459 375 0
event x y flags 0 458 375 0
event x y flags 0 456 375 0
event x y flags 0 455 375 0
event x y flags 0 452 374 0
event x y flags 0 448 368 0
event x y flags 0 443 365 0
event x y flags 0 432 354 0
event x y flags 0 425 346 0
event x y flags 0 417 336 0
event x y flags 0 394 311 0
event x y flags 0 358 284 0
event x y flags 0 330 263 0
event x y flags 0 309 248 0
event x y flags 0 296 239 0
event x y flags 0 291 235 0
event x y flags 0 290 235 0
event x y flags 1 290 235 1
event x y flags 4 290 235 0
event x y flags 0 290 235 0
event x y flags 0 293 235 0
event x y flags 0 295 236 0
event x y flags 0 297 236 0
event x y flags 0 298 237 0
event x y flags 0 305 238 0
event x y flags 0 310 237 0
event x y flags 0 316 234 0
event x y flags 0 31

In [ ]:
import cv2

def onChange(pos):
    pass

src = cv2.imread("IU.jpg", cv2.IMREAD_GRAYSCALE)

cv2.namedWindow("Trackbar Windows")

cv2.createTrackbar("threshold", "Trackbar Windows", 0, 255, onChange)
cv2.createTrackbar("maxValue", "Trackbar Windows", 0, 255, lambda x : x)

cv2.setTrackbarPos("threshold", "Trackbar Windows", 127)
cv2.setTrackbarPos("maxValue", "Trackbar Windows", 255)

while cv2.waitKey(1) != ord('q'):

    thresh = cv2.getTrackbarPos("threshold", "Trackbar Windows")
    maxval = cv2.getTrackbarPos("maxValue", "Trackbar Windows")

    _, binary = cv2.threshold(src, thresh, maxval, cv2.THRESH_BINARY)

    cv2.imshow("Trackbar Windows", binary)

cv2.destroyAllWindows()

In [ ]:
import cv2

src = cv2.imread("contours.webp", cv2.IMREAD_COLOR)

gray = cv2.cvtColor(src, cv2.COLOR_RGB2GRAY)
ret, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
binary = cv2.bitwise_not(binary)

contours, hierarchy = cv2.findContours(binary, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)

for i in range(len(contours)):
    cv2.drawContours(src, [contours[i]], 0, (0, 0, 255), 2)
    cv2.putText(src, str(i), tuple(contours[i][0][0]), cv2.FONT_HERSHEY_COMPLEX, 0.8, (0, 255, 0), 1)
    # print(i, hierarchy[0][i])
    cv2.imshow("src", src)
    cv2.waitKey(0)

cv2.destroyAllWindows()

In [ ]:
import cv2

src = cv2.imread("IU.jpg")
dst = src.copy()

gray = cv2.cvtColor(src, cv2.COLOR_RGB2GRAY)
corners = cv2.goodFeaturesToTrack(gray, 100, 0.01, 5, blockSize=3, useHarrisDetector=True, k=0.03)

for i in corners:
    cv2.circle(dst, tuple(map(int, i[0])), 3, (0, 0, 255), 2)

cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

src = cv2.imread("IU.jpg")
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
result = np.zeros((src.shape[0], 256), dtype=np.uint8)

hist = cv2.calcHist([gray], [0], None, [256], [0, 256])
cv2.normalize(hist, hist, 0, result.shape[0], cv2.NORM_MINMAX)

for x, y in enumerate(hist):
    cv2.line(result, (int(x), result.shape[0]), (int(x), result.shape[0] - int(y)), 255)

dst = np.hstack([gray, result])

cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import matplotlib.pyplot as plt

# 이미지 로드
img = cv2.imread('IU.jpg')

# OpenCV에서는 색상 채널 순서가 BGR이므로 RGB로 변환
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# 각 채널별로 히스토그램 계산
color = ('r', 'g', 'b')
for i, col in enumerate(color):
    histr = cv2.calcHist([img], [i], None, [256], [0,256])
    plt.plot(histr, color = col)
    plt.xlim([0,256])

plt.title('Histogram for color scale picture')
plt.show()

In [4]:
import cv2

src = cv2.imread("hats.webp", cv2.IMREAD_GRAYSCALE)
templit = cv2.imread("hat.webp", cv2.IMREAD_GRAYSCALE)
dst = cv2.imread("hats.webp")

result = cv2.matchTemplate(src, templit, cv2.TM_SQDIFF_NORMED)

minVal, maxVal, minLoc, maxLoc = cv2.minMaxLoc(result)
x, y = minLoc
h, w = templit.shape
print(result)
print(x, y)

dst = cv2.rectangle(dst, (x, y), (x +  w, y + h) , (0, 0, 255), 1)
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0.35533297 0.35373935 0.35233006 ... 0.38107723 0.38054636 0.38003504]
 [0.35876653 0.3570789  0.35559902 ... 0.37908155 0.37852526 0.37799665]
 [0.36310115 0.36135522 0.35979638 ... 0.37734947 0.37675878 0.3761936 ]
 ...
 [0.33359423 0.33221167 0.33134934 ... 0.5346984  0.52616715 0.51813215]
 [0.3475707  0.34613252 0.34522045 ... 0.5370005  0.528527   0.5205167 ]
 [0.36116964 0.3596826  0.35871062 ... 0.53968567 0.5312418  0.52326816]]
0 301
