In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
np_array = np.array(data)
n_np = torch.from_numpy(np_array)
n_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [10]:
shape = (2,3,) #shape 는 텐서의 차원을 나타내는 튜플
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

#rand : tensor([[0.2851, 0.4862, 0.0144], 
#               [0.4129, 0.0634, 0.8218]])
#ones : tensor([[1., 1., 1.], [1., 1., 1.]])
#zeros : tensor([[0., 0., 0.], [0., 0., 0.]])

ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.cuda.is_available()

False

In [22]:
tensor = torch.randint(0,3, (4,4))
tensor

tensor([[1, 2, 0, 1],
        [0, 1, 2, 2],
        [2, 2, 0, 0],
        [1, 1, 1, 2]])

In [36]:
q1_data_1 = [[1,2],[3,4]]
q1_data_2 = [[5,6],[7,8]]
t_data_1 = torch.tensor(q1_data_1)
t_data_2 = torch.tensor(q1_data_2)

q1_s1 = t_data_1 @ t_data_2
print(q1_s1)
print(q1_s1.sum().item())
q1_s2 = torch.mul(t_data_1, t_data_2)
print(q1_s2)

tensor([[19, 22],
        [43, 50]])
134
tensor([[ 5, 12],
        [21, 32]])
