In [13]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# 데이터셋
x = torch.FloatTensor( [[ 7.71011738e-01, -3.13508197e-01,  5.42352572e-01],
                            [-1.85861239e+00,  2.16116006e-01,  5.08396243e-01],
                            [ 5.39058321e-01, -1.11792545e+00,  4.15393930e-02],
                            [-6.37655012e-01, -2.36184031e-01, -3.38821966e-01],
                            [-8.78107893e-01,  9.02525097e-03, -7.47870949e-01],
                            [-9.88779049e-01,  2.56570452e-01, -1.56434170e-01],
                            [-1.53495196e-01, -1.42121723e+00, -1.18761229e+00],
                            [-6.34679305e-01,  1.27837923e+00,  4.33496330e-01],
                            [-7.44707629e-02, -3.75669423e-01, -3.81092518e-01],
                            [ 9.76147160e-06, -8.44213704e-01,  5.01857207e-01],
                            [ 2.29220801e+00,  5.51454045e-01, -9.09007615e-01],
                            [-8.41747366e-01, -1.79343559e+00,  1.64027081e+00],
                            [ 4.79705919e-02,  6.11340780e-01, -3.35677339e-01],
                            [ 1.17500122e+00, -1.91304965e-02, -5.96159700e-01],
                            [-1.05795222e+00, -1.24528809e+00,  5.02881417e-01],
                            [-2.43476758e+00,  2.23136679e+00, -2.69056960e-01],
                            [ 1.35963386e+00,  3.70444537e-01,  1.12726505e-01],
                            [ 1.00036589e+00,  8.77102184e-02, -8.29135289e-01],
                            [-2.13619610e+00, -5.62668272e-02, -4.16757847e-01],
                            [ 1.46767801e+00,  1.73118467e+00, -1.86809065e+00]])

y = torch.FloatTensor([[  96.68704955],
                            [-158.98008532],
                            [  54.49974683],
                            [ -71.2832092 ],
                            [-109.68370597],
                            [ -96.20277494],
                            [ -61.52618908],
                            [ -38.24501686],
                            [ -19.32846993],
                            [  16.24620599],
                            [ 198.60935931],
                            [ -31.37236913],
                            [  -0.41438801],
                            [  97.7887465 ],
                            [ -88.92656277],
                            [-234.84110943],
                            [ 140.94339104],
                            [  72.84533909],
                            [-220.9413211 ],
                            [  90.02679734]])


# 다중 선형 회귀 클래스
class MultiLinearRegression(nn.Module):
    def __init__(self):
        super(MultiLinearRegression, self).__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)


model = MultiLinearRegression()

x1=torch.tensor(x)
y1=torch.tensor(y)

w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# 손실 함수와 옵티마이저
loss_fn = nn.MSELoss()  # 평균 제곱 오차
optimizer = optim.SGD(model.parameters(), lr=1e-3)

# 학습
epochs = 2000
for epoch in range(epochs + 1):
    prediction = model(x)

    loss = loss_fn(prediction, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 ==0:
      print('Epoch {:4d}/{} prediction: {} Cost: {:.6f}'.format(
          epoch, epochs, prediction.squeeze().detach(), loss.item()
      ))
    

# 예측
model.eval()
x_test = torch.tensor([[90, 88, 93]], dtype=torch.float32)
y_test = model(x_test)
#print(f"예측 값: {y_test.squeeze().detach()}")
 
model.linear.weight



C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19256\3465970873.py:62: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x1=torch.tensor(x)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19256\3465970873.py:63: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y1=torch.tensor(y)


Epoch    0/2000 prediction: tensor([ 0.7769,  0.4000,  0.7560,  0.3955,  0.2301,  0.3243,  0.4267,  0.3461,
         0.4682,  0.7674,  0.4480,  1.1063,  0.3364,  0.4942,  0.7166, -0.1724,
         0.6268,  0.4011,  0.1856, -0.0637]) Cost: 13241.481445
Epoch  100/2000 prediction: tensor([ 15.8102, -48.3580,  11.8792, -17.2205, -22.8389, -26.5714,  -2.9239,
        -20.0841,  -3.3820,  -2.0718,  53.2360, -22.5857,  -1.7671,  26.6031,
        -27.1062, -63.9334,  29.6725,  22.5355, -53.5561,  32.9759]) Cost: 7287.898438
Epoch  200/2000 prediction: tensor([  27.5258,  -83.2833,   20.4639,  -30.0407,  -40.0032,  -46.0899,
          -5.8382,  -34.5695,   -6.1733,   -3.3442,   91.1921,  -38.0082,
          -3.3997,   45.4375,  -46.5401, -110.7373,   51.1588,   38.2671,
         -92.8183,   55.5746]) Cost: 4140.033203
Epoch  300/2000 prediction: tensor([  36.7662, -108.2559,   27.1179,  -39.4014,  -52.8576,  -60.2634,
          -8.4601,  -44.7175,   -8.2109,   -3.5984,  118.5320,  -47.7282,
  

Parameter containing:
tensor([[93.7705, -1.3601, 20.9094]], requires_grad=True)

In [15]:
model(torch.Tensor([1,2,3]))

tensor([152.2637], grad_fn=<ViewBackward0>)

In [16]:
model.linear.bias

Parameter containing:
tensor([-1.5146], requires_grad=True)